# Copyright (c) 2016-2021 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Sams
site_url: https://unclsams.github.io/hyperscaler-glossary/
site_author: Sam
site_description: >-
  Create a branded static site from a set of Markdown files to host the
  documentation of your Open Source or commercial project

# Repository
repo_name: FEEDBACK/ISSUES
repo_url: https://github.com/unclsams/hyperscaler-glossary/issues
edit_uri: ""


# Copyright statement in Footer
copyright: <a href="/about/">Copyright (C) 2021 Mkdocs</a>.

# Configuration
theme:
  name: null
  custom_dir: !ENV [THEME_DIR, "material"]

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  
  language: en
  features:
    - content.code.annotate
    - content.tabs.link
    # - header.autohide
    # - navigation.expand
    # - navigation.indexes
    # - navigation.instant
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
  palette:
    - scheme: default
      primary: grey
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    #text: Roboto
    #code: Roboto Mono
    text: 'IBM Plex Sans'
    code: 'IBM Plex Mono'
  #favicon: assets/favicon.png
  icon:
  logo: kyndryl2.png
  favicon: 'kyndryl2.png'

extra_css:
  - 'extra.css'
  - 'extra-pagesize.css'

# Plugins
plugins:
  - search
  #- redirects:
  #    redirect_maps:
  #      changelog/insiders.md: insiders/changelog.md
  #      extensions/admonition.md: reference/admonitions.md
  #      extensions/codehilite.md: reference/code-blocks.md
  #      extensions/footnotes.md: reference/footnotes.md
  #      extensions/metadata.md: reference/meta-tags.md
  #      extensions/permalinks.md: setup/setting-up-navigation.md #permalink
  #      extensions/pymdown.md: reference/admonitions.md
  #      plugins/revision-date.md: setup/adding-a-git-repository.md #revision-date
  #      plugins/search.md: setup/setting-up-site-search.md
  #      releases/4.md: upgrading.md #upgrading-from-4x-to-5x
  #      releases/5.md: upgrading.md #upgrading-from-3x-to-4x
  #      releases/changelog.md: changelog.md
  #      setup/adding-social-links.md: setup/setting-up-the-footer.md
  #      sponsorship.md: insiders/index.md
  - minify:
      minify_html: true

# Customization
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
    #- icon: kyndryl2.png
      link: 'https://github.kyndryl.net/OCTO/azure/'
      name:  FEEDBACK & ISSUES
    #- icon: fontawesome/brands/github
    #  link: https://github.com/squidfunk
    #- icon: fontawesome/brands/gitter
    #  link: https://gitter.im/squidfunk/mkdocs-material
    #- icon: fontawesome/brands/docker
    #  link: https://hub.docker.com/r/squidfunk/mkdocs-material/
    #- icon: fontawesome/brands/twitter
    #  link: https://twitter.com/squidfunk
    #- icon: fontawesome/brands/linkedin
    #  link: https://linkedin.com/in/squidfunk/
    #- icon: fontawesome/brands/instagram
    #  link: https://instagram.com/squidfunk

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: ⚓︎
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  #- pymdownx.emoji:
  #    emoji_index: !!python/name:materialx.emoji.twemoji
  #    emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
 
# Footer notice "Made with Material for Mkdocs"
#extra:
#  generator: false

# Page tree
nav:
      - Home: 
        - Introduction: 'index.md'
        - Scope: 'home/scope.md'
        - Pre-Requisite Learning: 'home/prereq-learning.md'
      - Adoption & Design:
          - Strategy & Planning:
              - 'Strategy & Planning Overview': 'stratplan/stratplanoverview.md'
              - 'Cloud Adoption Strategy': 'stratplan/adoptionstrategy.md'
              - 'Plan': 'stratplan/adoptionplan.md'
          - Landing Zone Design:
              - 'Overview & Scope': 'lzdesign/lzdesignoverview.md'
              - 'Design Approach': 'lzdesign/lzdesignapproach.md'
              - '1.Enterprise Enrollment': 'lzdesign/eaenrolment.md'
              - '2.Identity & Access': 'lzdesign/iam.md'
              - '3.Organization Mgmt': 'lzdesign/orgmgmt.md'
              - '4.Network': 'lzdesign/nwtopology.md'
              - '5.Monitoring & Mgmt': 'lzdesign/monitoringmgmt.md'
              - '6.Governance & Compliance': 'lzdesign/govcomp.md'
              - '7.Backup & DR': 'lzdesign/bcdr.md'
              - '8.Platform Automation': 'lzdesign/platformauto.md'
          - Automations:
              - 'Automation Framework': 'automation/automation/automation-framework.md'
              - 'Automation Architecture': 'automation/automation/automation-architecture.md'
              - 'Make Manage Automation': 'automation/automation/makemanage.md'
              - 'Azure Automation Options': 'automation/automation/azure-automationoptions.md'
          - Azure LightHouse:
              - 'LightHouse Enablement': 'automation/lighthouse/lh-enableguide.md'
              - 'LightHouse Administration': 'automation/lighthouse/lh-adminguide.md'
      - Azure Resources & Services:
        - 'Azure Compute': 'resource-service/compute.md'
        - 'VM Agents': 'resource-service/vmagents.md'
        - 'Azure Storage': 'resource-service/storage.md'
        - 'Azure Kubernetes Service': 'resource-service/aks.md'
      - Examples - Design & Implementation:
          - Landing Zone Design - Sample Workload 1:
              - 'Workload Description': 'lzdesignsample1/wldescription.md'
              - '1.Enterprise Enrollment & Azure AD Tenants': 'lzdesignsample1/eaenrol.md'
              - '2.Identity & Access Management': 'lzdesignsample1/idaccess.md'
              - '3.Organization & Management Group': 'lzdesignsample1/organdmgmt.md'
              - '4.Network Topology & Connectivity': 'lzdesignsample1/nwtopo.md'
              - '5.Monitoring & Management': 'lzdesignsample1/monitoringmgmt.md'
              - '6.Business Continuity & Disaster Recovery': 'lzdesignsample1/backupdr.md'
              - '7.Governance & Compliance': 'lzdesignsample1/govcomp.md'
              - '8.Platform Automation & DevOps': 'lzdesignsample1/platformauto.md'
          - Virtual WAN - Design and Implementation:
              - 'Overview and Link to Details': 'virtualwan/overview.md'
      - Operations Automation (IN PROGRESS):
          - Automations:
              - 'Automation UseCases': 'automation/automation/automation-usecases.md'
              - 'Automation Architecture': 'automation/automation/automation-architecture.md'
              - 'Make Manage Automation': 'automation/automation/makemanage.md'
              - 'Azure Automation Options': 'automation/automation/azure-automationoptions.md'
          - Azure LightHouse:
              - 'LightHouse Enablement': 'automation/lighthouse/lh-enableguide.md'
              - 'LightHouse Administration': 'automation/lighthouse/lh-adminguide.md'
      - About:
        - Contributors: 'about/1authors.md'
